trigger:
- master

pool:
  name: fhv-linux-pool

stages:
- stage: Build
  displayName: Build the Application
  jobs:
  - job: Build
    displayName: Gradle Build
    steps:
    - checkout: self

    - task: Gradle@3
      displayName: Run Gradle Build
      inputs:
        gradleWrapperFile: 'gradlew'
        tasks: 'build'
        options: '-Dorg.gradle.jvmargs=-Xmx3072m'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
