# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.

trigger:
- master

pool:
  name: fhv-linux-pool

steps:
- checkout: self

- task: Gradle@3
  displayName: 'Build & Test with Gradle'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/test/*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # or whatever version you need
    gradleOptions: '-Xmx3072m'
    sonarQubeRunAnalysis: false

- task: PublishTestResults@2
  condition: always()  # Publish results even if tests fail
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/build/test-results/test/*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Test Results'

- task: PublishCodeCoverageResults@1
  condition: always()
  inputs:
    codeCoverageTool: 'JaCoCo'
    summaryFileLocation: '**/build/reports/jacoco/test/*.xml'
    reportDirectory: '**/build/reports/jacoco/test/html'