version: "3.8"

services:
  eventapp:
    image: localhost:5000/natureconnect:1.0
    container_name: natureconnect
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped
